name: Publish Docker image
on:
  push:
    branches:
      - master
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set Docker image version
        run: cat ./VERSION >> $VERSION
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: zconger
          password: ${{ secrets.DOCKER_ZCONGER }}
          repository: zconger/rps
          tags: zconger/rps:${VERSION}
